# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/node:9.8
      environment:
        NPM_CONFIG_LOGLEVEL: error # make npm commands less noisy

restore_cache: &restore_cache
  keys:
    - code-{{ .Branch }}-{{ checksum ".nvmrc" }}-{{ checksum "package.json" }}
    - code-master-{{ checksum ".nvmrc" }}-{{ checksum "package.json" }}

save_cache: &save_cache
  key: code-{{ .Branch }}-{{ checksum ".nvmrc" }}-{{ checksum "package.json" }}
  paths:
    - node_modules

version: 2
jobs:
  build: 
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: npm install
      - run: npm run eslint:ci
      - run: npm run test
      - save_cache: *save_cache

